#pragma once

#define VIAL_KEYBOARD_UID {0xAA, 0xCB, 0xDE, 0x92, 0xE8, 0x78, 0x46, 0xAC}

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8

#define VIALRGB_NO_DIRECT