#pragma once

#define VIAL_KEYBOARD_UID {0x95, 0x04, 0x46, 0xF5, 0x77, 0xDE, 0x7B, 0xD7}

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 17
#define BOOTMAGIC_LITE_ROW_RIGHT 7
#define BOOTMAGIC_LITE_COLUMN_RIGHT 3

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8

#define VIALRGB_NO_DIRECT