#pragma once

#define VIAL_KEYBOARD_UID {0xA9, 0x5E, 0xBD, 0xCA, 0x7B, 0xFC, 0x6A, 0x2A}

#define BOOTMAGIC_LITE_ROW_RIGHT 5
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8

#define VIALRGB_NO_DIRECT