#pragma once

#define VIAL_KEYBOARD_UID {0x4C, 0xA0, 0x9B, 0x57, 0x92, 0x61, 0x1E, 0x6B}

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 15
#define BOOTMAGIC_LITE_ROW_RIGHT 5
#define BOOTMAGIC_LITE_COLUMN_RIGHT 3

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8

#define VIALRGB_NO_DIRECT
