#pragma once

#define VIAL_KEYBOARD_UID {0x81, 0xB1, 0x0E, 0x54, 0xF3, 0x2A, 0x98, 0x16}

#define BOOTMAGIC_LITE_ROW_RIGHT 5
#define BOOTMAGIC_LITE_COLUMN_RIGHT 0

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8

#define VIALRGB_NO_DIRECT